### ISSUE TITLE
What's the different between BertScore and BertScore Art?

### ISSUE THREAD

**Issue by ariecattan** [artidoro/frank#8]

**Comment by chenllliang** [comment]
same question ! looking forward to author's reply !

**Comment by artidoro** [comment]
Hello! Thanks for your question.

BertScore compares two texts, usually the generated one and the reference. BertScore Art is run using the article as reference, while BertScore is using the target summary (provided as part of the summarization dataset) as reference. In theory, using the article should be better when measuring the factuality of a generated summary since the reference might not contain some important information. 

Let me know if you need more information on this.

**Comment by ariecattan** [comment]
Thanks for the answer!

**Comment by chenllliang** [comment]
Thanks. I've submitted one result using SimCSE to do the evaluation.
